### ISSUE TITLE
###Header3 formats as all CAPS

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#10]
**Describe the bug**
###Header3 formats as all CAPS

![image](https://user-images.githubusercontent.com/51930500/68906412-02186d00-06f9-11ea-9051-df3d20da790e.png)

github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/installation-and-upgrades/installation-guide/installation-overview.md

site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/html/docs/installation-and-upgrades/installation-guide/installation-overview.html

**Comment by Alec-Shay** [comment]
@jrhoun   Just as another note, it's also problematic that these do not render highlighted text (text in tick marks like `ClassName`). This slightly damages readability for class names in sub-headers.

**Comment by jrhoun** [comment]
![image](https://user-images.githubusercontent.com/597214/68963419-bc58b480-078b-11ea-881f-81c2b9df21c6.png)

^Example

**Comment by rdai10** [comment]
> @jrhoun @andrewwilkinsonLR Just as another note, it's also problematic that these do not render highlighted text (text in tick marks like `ClassName`). This slightly damages readability for class names in sub-headers.

@jrhoun Do we want to render <code> in headings?

**Comment by jrhoun** [comment]
I think in the case of the developer tutorial material we do really want to highlight that a given section is covering the usage of a particular class or interface, yes - I think we do in those scenarios. In the dev guide section though - as far as I can tell it doesn't mess up the right nav TOC because the headers are h3+ - not sure if that helps.
