### ISSUE TITLE
Breadcrumb currently not functioning correctly

### ISSUE THREAD

**Issue by jrhoun** [liferay/liferay-learn#38]
This impacts usability of the site by preventing a user from knowing where they are at.
This also has an impact on the functionality of the 'go back' left nav utility.

**Comment by jrhoun** [comment]
This issue is currently being looked at by mcd and bchan. This is expected to fix #35.

**Comment by sez11a** [comment]
I sent a pull fixing this here: https://github.com/rdai10/liferay-learn/pull/2/commits/9a111b9276bbd74fde0d771323db0a2fb8da7414

**Comment by holatuwol** [comment]
There was also a mistake in the way I was generating the relative paths.

https://github.com/rdai10/liferay-learn/pull/3

**Comment by sez11a** [comment]
@holatuwol Isn't this a rather heavy handed fix, especially when it can be fixed by doing the toctree files correctly? Please see my PR to @rdai10

**Comment by holatuwol** [comment]
@sez11a : Technically, yes.

I'd also suggested the idea of doing the toctree files correctly as a potential solution last week, but there were README.md files that needed to be in the breadcrumbs. Since they're markdown files, they can only be leaves in the toctree, since AutoStructify is pretty limited.

There weren't any plans (at least at that time) to rewrite everything to be rst. If those plans have changed, we could remove the custom HTMLBuilder and go back and update the rst files to have proper hierarchy.
